### ISSUE TITLE
Request: Statusbar script

### ISSUE THREAD

**Issue by frank604** [TaylanTatli/dwm#1]
Hi Taylan,

I've been playing with your dwm setup and am encountering a weird statusbar behavior.  There is a gap between where my dwm statusbar is displayed and where the systray is.  Could you share your statusbar script so I can see if problem exists on just mine?  Thanks.

**Comment by TaylanTatli** [comment]
There was some problem with statusbar. So I used spaces to make it work.  I no longer using DWM. Here is mine, but it's binary and I don't remember where I found source. https://github.com/TaylanTatli/dotfiles/blob/master/bin/dwmstatus

**Comment by frank604** [comment]
Well, that was quick.  Great to know.  Thanks for the link and info.
